<?php
/**
 * Created by PhpStorm.
 * User: feng
 * Date: 2020/6/21
 * Time: 13:21
 */

namespace common\models;


class CompanyInfoModel extends BaseActiveRecord
{
    public static function tableName()
    {
        return 'company_info';
    }

    public function beforeSave($insert)
    {
        file_put_contents('test.txt', print_r($insert, true));
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}