<?php
/**
 * Created by PhpStorm.
 * User: feng
 * Date: 2020/6/27
 * Time: 15:13
 */

namespace frontend\controllers;


use common\models\ArticleModel;
use common\models\CompanyInfoModel;
use common\models\NavigationModel;
use yii\web\Controller;

class BaseController extends Controller
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function init(){
        parent::init();
        //获取公司信息
        $company = CompanyInfoModel::findOne(['id' => 1]);
        if (isset($company['logo']) && $company['logo']){
            $company['logo'] = \Yii::$app->params['backendUrl'] . $company['logo'];
        }

        //获取导航菜单
        $navList = NavigationModel::find()->orderBy('sort')->where(['status' => 1])->asArray()->all();
        $newNav = [];
        $footNavList = [];
        foreach ($navList as $k => $v){
            if ($v['level'] == 0){
                $newNav[$v['id']] = $v;
                unset($navList[$k]);
                foreach ($navList as $k2 => $v2){
                    if ($v2['pid'] == $v['id']){
                        foreach ($navList as $k3 => $v3){
                            if ($v3['pid'] == $v2['id']) {
                                $v2['child'][] = $v3;
                                unset($navList[$k3]);
                            }
                        }
                        $newNav[$v['id']]['child'][] = $v2;
                        unset($navList[$k2]);
                    }
                }
            }elseif ($v['level'] == -1){
                $footNavList[] = [
                    'name' => $v['name'],
                    'url' => $v['url'],
                ];
            }
        }

        //底部两条 latest news
        $latestNews = ArticleModel::instance()->find()->where(['>', 'news', 0])
            ->select('id, title, created_at')
            ->orderBy('news')->limit(2)->asArray()->all();
        foreach ($latestNews as $k => $v){
            $latestNews[$k]['url'] = $this->getArticleUrlById($v['id']);
        }

        \Yii::$app->view->params['latestNews'] = $latestNews;
        \Yii::$app->view->params['footNavList'] = $footNavList;
        \Yii::$app->view->params['company'] = $company;
        \Yii::$app->view->params['navList'] = $newNav;
    }

    protected function getArticleUrlById($id){
        return '/index.php/article?id='.$id;
    }

    protected function curlGet($url){
        $header = array(
            'Accept: application/json',
        );
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_HEADER, 0);
        curl_setopt($curl, CURLOPT_TIMEOUT, 1);
        curl_setopt($curl, CURLOPT_HTTPHEADER, $header);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
        $data = curl_exec($curl);

        if (curl_error($curl)) {
            return "Error: " . curl_error($curl);
        } else {
            curl_close($curl);
            return $data;
        }
    }
}